### PR TITLE
Add Prelude subpackage

### PR DESCRIPTION
**Pull request by matthewsanetra**
This is a draft PR of an (experimental?) design for a "fundamental" package.

Imagine this subpackage as a collection of builtins. That is, to use it, one would:
```go
import (
  . "github.com/thecsw/gana/prelude"
)
```
This will allow you to use functions such as `Some` without writing `prelude.Some`.

Importing in to the local scope is looked down upon in Go, with the main reason being future package versions can introduce new symbols that will clash with your locally defined symbols.
I believe we can circumvent this by defining a strict spec of exported symbols in `prelude`, keeping it to a minimum and anything new is a major version bump (once we start versioning).

I have currently added the `Option` and `Result` types, along with some defined methods and their relevant tests.

The current "reserved" symbols are: `Option`, `Some`, `SomeT`, `None`, `NoneT`, `Maybe`, `Result`, `Ok`, `OkT`, `Err`, `ErrT`, `Try`.

I will continue experimenting with the ergonomics, and rewrite the rest of the `gana` package to use these features "idiomatically" (me figuring out what looks the best and changing this API).

### CODE REVIEW

**Comment by thecsw** [comment]
Fantastic! For myself and future READMEs/guidelines, how should we use `Option` and `Result`? In essence, what is the differences between their usages.

If I were to write a function that reads a file, which of course can fail, when I successfully read a file or stumble upon an error, should I return an `Option` (`None` for failure) or `Result`?

**Comment by thecsw** [comment]
Note on the naked import -- I like the idea if we *pinky promise* to never change the included symbols, therefore not accidentally breaking users' environments.

Of course, many developers are terrible skeptics (rightfully so). We can tell them that we will keep major versions of `gana` super strict on `prelude`'s symbols and only major versions would have new symbols (if any added).

Otherwise, they can always import it as `prelude` or `p` if they don't want to type the whole sub-packages name.

**Comment by matthewsanetra** [comment]
@thecsw 

If it is anything to do with error handling, use Result, even if you don't want to return any error object - just return a `Result[T, unit type]` (is there one in Go? should we make one or have users make their own empty structs? or do we advocate `interface{}`?). This follows the same ideology as Rust.

Re. how to use the types, replace the Go idioms of `val, err := f()` or `val, ok := f()` with `res := f()` where `f` now returns `Option` or `Result`. If `f` is external and doesn't use these types, you can easily wrap it with `Try` (for `val, err`) or `Maybe` (for `val, ok`) like so: `res := Maybe(f())`. You can always convert back to the "spread" form by calling `.Unpack()`.

**Comment by thecsw** [comment]
Agreed, @matthewsanetra, I prefer if users used `interface{}` as it's go idiomatic and more intuitive. Do you think we can merge this PR?

**Comment by matthewsanetra** [comment]
I haven't had time to work on this - I'm so sorry! I will take it out of draft mode if you think it is good enough or want to make your own changes/additions.

**Comment by thecsw** [comment]
nw at all—i've played with it and lgtm, thanks!

**Review by thecsw — APPROVED** [review]
above

**Pull request merged**
